// ---------------------------------------------------------------------------
// main.bicep — Azure SRE Agent Demo Lab, deployed at resource group scope.
//
// Resource-group scope (rather than subscription scope) is intentional: it
// keeps the required permission down to Contributor + User Access
// Administrator on a single resource group, which is what a customer is most
// likely to be granted when they clone this lab into their own subscription.
// scripts/deploy.sh creates the resource group first.
//
// Nothing here is pinned to a subscription, tenant, region, object ID, public
// IP, Kubernetes version or password — all of those arrive as parameters.
// ---------------------------------------------------------------------------

targetScope = 'resourceGroup'

@description('Azure region for all resources. Defaults to the resource group location.')
param location string = resourceGroup().location

@description('Short suffix that makes every resource name unique within the subscription.')
@minLength(3)
@maxLength(12)
param suffix string

@description('CIDRs permitted to reach SSH, the Scenario Controller UI and the Magic 8 Ball load balancer.')
param adminCidrs array

@description('SSH public key installed on both lab VMs. Password authentication is disabled.')
param adminPublicKey string

@description('Administrator username on both lab VMs.')
param adminUsername string = 'sreadmin'

@description('Password for the PostgreSQL application role. Generated by the deploy script.')
@secure()
param postgresAppPassword string

@description('Password for the PostgreSQL scenario role. Generated by the deploy script.')
@secure()
param postgresScenarioPassword string

@description('Size of the App VM.')
param appVmSize string = 'Standard_B2s'

@description('Size of the PostgreSQL VM.')
param postgresVmSize string = 'Standard_B2s'

@description('AKS system node pool VM size. The deploy script validates regional availability first.')
param aksNodeVmSize string = 'Standard_D2as_v7'

@description('Baseline AKS node count. Scenario 02 is remediated by scaling above this value.')
@minValue(1)
@maxValue(5)
param aksBaselineNodeCount int = 1

@description('Kubernetes version. Empty accepts the regional AKS default.')
param kubernetesVersion string = ''

@description('Size of the dedicated demo data disk targeted by scenario 01.')
param demoDataDiskSizeGb int = 16

@description('PostgreSQL connection ceiling. Low on purpose so scenario 04 saturates quickly.')
param postgresMaxConnections int = 50

@description('Application database name.')
param postgresDatabase string = 'sre_demo'

@description('Application database role.')
param postgresAppUser string = 'sre_app'

@description('Database role dedicated to the connection-exhaustion scenario.')
param postgresScenarioUser string = 'sre_scenario'

@description('Object ID of the principal running the deployment. Granted Key Vault Secrets Officer so the deploy script can store generated passwords.')
param deployerObjectId string = ''

@description('Create role assignments. Set false if the deploying principal lacks User Access Administrator; the deploy script then prints the equivalent commands.')
param assignRoles bool = true

@description('Also create an Azure SRE Agent. Off by default: it is a chargeable managed service and is not offered in every region the rest of the lab runs in.')
param deploySreAgent bool = false

@description('Region for the SRE Agent. Separate from the lab location because the two do not offer the same regions; deploy.sh validates this before submitting.')
param sreAgentLocation string = location

@description('How the agent may act. Review pauses for human approval before every remediation.')
@allowed([
  'ReadOnly'
  'Review'
  'Autonomous'
])
param sreAgentMode string = 'Review'

@description('Log Analytics daily ingestion cap in GB. Protects demo cost.')
param logAnalyticsDailyQuotaGb int = 2

@description('Tags applied to every resource in the lab.')
param tags object = {
  project: 'azure-sre-agent-demo'
  environment: 'demo'
  managedBy: 'bicep'
  purpose: 'sre-training'
}

module network 'modules/network.bicep' = {
  name: 'deploy-network'
  params: {
    location: location
    tags: tags
    suffix: suffix
    adminCidrs: adminCidrs
  }
}

module monitoring 'modules/monitoring.bicep' = {
  name: 'deploy-monitoring'
  params: {
    location: location
    tags: tags
    suffix: suffix
    dailyQuotaGb: logAnalyticsDailyQuotaGb
  }
}

module registry 'modules/acr.bicep' = {
  name: 'deploy-acr'
  params: {
    location: location
    tags: tags
    suffix: suffix
  }
}

module security 'modules/security.bicep' = {
  name: 'deploy-security'
  params: {
    location: location
    tags: tags
    suffix: suffix
  }
}

module postgresVm 'modules/postgres-vm.bicep' = {
  name: 'deploy-postgres-vm'
  params: {
    location: location
    tags: tags
    suffix: suffix
    subnetId: network.outputs.databaseSubnetId
    vmSize: postgresVmSize
    adminUsername: adminUsername
    adminPublicKey: adminPublicKey
    identityId: security.outputs.identityId
    dataCollectionRuleId: monitoring.outputs.dataCollectionRuleId
    databaseName: postgresDatabase
    appUsername: postgresAppUser
    scenarioUsername: postgresScenarioUser
    appPassword: postgresAppPassword
    scenarioPassword: postgresScenarioPassword
    maxConnections: postgresMaxConnections
    allowedClientCidrs: [
      network.outputs.appSubnetPrefix
      network.outputs.aksSubnetPrefix
    ]
  }
}

module appVm 'modules/app-vm.bicep' = {
  name: 'deploy-app-vm'
  params: {
    location: location
    tags: tags
    suffix: suffix
    subnetId: network.outputs.appSubnetId
    vmSize: appVmSize
    adminUsername: adminUsername
    adminPublicKey: adminPublicKey
    demoDataDiskSizeGb: demoDataDiskSizeGb
    identityId: security.outputs.identityId
    dataCollectionRuleId: monitoring.outputs.dataCollectionRuleId
  }
}

module aks 'modules/aks.bicep' = {
  name: 'deploy-aks'
  params: {
    location: location
    tags: tags
    suffix: suffix
    subnetId: network.outputs.aksSubnetId
    workspaceId: monitoring.outputs.workspaceId
    nodeVmSize: aksNodeVmSize
    baselineNodeCount: aksBaselineNodeCount
    kubernetesVersion: kubernetesVersion
    containerInsightsRuleId: monitoring.outputs.containerInsightsRuleId
  }
}

module alerts 'modules/alerts.bicep' = {
  name: 'deploy-alerts'
  params: {
    location: location
    tags: tags
    suffix: suffix
    workspaceId: monitoring.outputs.workspaceId
  }
}

// --- Role assignments -------------------------------------------------------
// Delegated to a module so that principal IDs, which only exist once the
// identity and cluster are created, arrive as parameters and therefore satisfy
// the "role assignment name must be known at deployment start" rule.

module rbac 'modules/rbac.bicep' = if (assignRoles) {
  name: 'deploy-rbac'
  params: {
    acrName: registry.outputs.registryName
    keyVaultName: security.outputs.keyVaultName
    labIdentityPrincipalId: security.outputs.identityPrincipalId
    kubeletIdentityObjectId: aks.outputs.kubeletIdentityObjectId
    aksClusterPrincipalId: aks.outputs.clusterPrincipalId
    vnetName: network.outputs.vnetName
    deployerObjectId: deployerObjectId
  }
}

module sreAgent 'modules/sre-agent.bicep' = if (deploySreAgent) {
  name: 'deploy-sre-agent'
  params: {
    name: 'sre-agent-${suffix}'
    location: sreAgentLocation
    mode: sreAgentMode
    appInsightsAppId: monitoring.outputs.appInsightsAppId
    appInsightsConnectionString: monitoring.outputs.appInsightsConnectionString
    deployerObjectId: assignRoles ? deployerObjectId : ''
    tags: tags
  }
}

// --- Outputs consumed by scripts/deploy.sh ---------------------------------

output location string = location
output suffix string = suffix
output resourceGroupName string = resourceGroup().name

output acrName string = registry.outputs.registryName
output acrLoginServer string = registry.outputs.loginServer

output logAnalyticsWorkspaceId string = monitoring.outputs.workspaceId
output logAnalyticsWorkspaceName string = monitoring.outputs.workspaceName
output logAnalyticsCustomerId string = monitoring.outputs.workspaceCustomerId
output appInsightsName string = monitoring.outputs.appInsightsName
output appInsightsId string = monitoring.outputs.appInsightsId
@secure()
output appInsightsConnectionString string = monitoring.outputs.appInsightsConnectionString

output keyVaultName string = security.outputs.keyVaultName
output keyVaultUri string = security.outputs.keyVaultUri
output labIdentityId string = security.outputs.identityId
output labIdentityClientId string = security.outputs.identityClientId
output labIdentityPrincipalId string = security.outputs.identityPrincipalId

output appVmName string = appVm.outputs.vmName
output appVmPublicIp string = appVm.outputs.publicIp
output appVmPrivateIp string = appVm.outputs.privateIp
output appVmFqdn string = appVm.outputs.fqdn
output appVmAdminUsername string = appVm.outputs.adminUsername
output demoMountPath string = appVm.outputs.demoMountPath

output postgresVmName string = postgresVm.outputs.vmName
output postgresPrivateIp string = postgresVm.outputs.privateIp
output postgresDatabaseName string = postgresVm.outputs.databaseName
output postgresAppUsername string = postgresVm.outputs.appUsername
output postgresScenarioUsername string = postgresVm.outputs.scenarioUsername
output postgresMaxConnections int = postgresVm.outputs.maxConnections

output aksClusterName string = aks.outputs.clusterName
output aksNodeResourceGroup string = aks.outputs.nodeResourceGroup
output aksKubernetesVersion string = aks.outputs.kubernetesVersion
output aksNodeVmSize string = aks.outputs.nodeVmSize
output aksBaselineNodeCount int = aks.outputs.baselineNodeCount
output aksSystemNodePoolName string = aks.outputs.systemNodePoolName

output databaseNsgName string = network.outputs.databaseNsgName
output vnetName string = network.outputs.vnetName
output alertRuleNames array = alerts.outputs.alertRuleNames

output sreAgentDeployed bool = deploySreAgent
output sreAgentName string = sreAgent.?outputs.agentName ?? ''
output sreAgentId string = sreAgent.?outputs.agentId ?? ''
output sreAgentRegion string = sreAgent.?outputs.agentLocation ?? ''
output sreAgentActionMode string = sreAgent.?outputs.agentMode ?? ''
output sreAgentPrincipalId string = sreAgent.?outputs.principalId ?? ''
output sreAgentEndpoint string = sreAgent.?outputs.agentEndpoint ?? ''
